import * as React from "react"
import { DiligenceProfile } from "@/types/profile"
import { ProfileHeader } from "./ProfileHeader"
import { NetWorthCard } from "./NetWorthCard"
import { CareerTimeline } from "./CareerTimeline"
import { EntityGrids } from "./EntityGrids"
import { ConcernsPanel } from "./ConcernsPanel"
import { SourcesPanel } from "./SourcesPanel"
import { ShieldCheck } from "lucide-react"
import Link from "next/link"

export function ProfileDashboard({ profile }: { profile: DiligenceProfile }) {
  return (
    <div className="min-h-screen bg-slate-50 font-sans">
      {/* Top Navbar */}
      <header className="bg-white border-b border-gray-200 sticky top-0 z-50">
        <div className="max-w-[1200px] mx-auto px-6 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2 hover:opacity-80 transition-opacity">
            <div className="bg-[#0a2540] p-1.5 rounded-md">
              <ShieldCheck className="h-5 w-5 text-white" />
            </div>
            <span className="font-extrabold text-[#0a2540] text-xl tracking-tight">Diligencify</span>
          </Link>
          <div className="text-xs font-semibold text-gray-500 bg-gray-100 px-4 py-1.5 rounded-full">
            Profile Report
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-[1200px] mx-auto px-6 py-10 space-y-8">
        
        {/* Full-width Concerns Panel */}
        <ConcernsPanel concerns={profile.concerns} />

        {/* Top Grid: Profile Header (Left) + NetWorth (Right) */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          <div className="lg:col-span-2">
            <ProfileHeader profile={profile} />
          </div>
          <div className="lg:col-span-1">
            <NetWorthCard netWorth={profile.net_worth} />
          </div>
        </div>

        {/* Bottom Content Area */}
        <div className="space-y-8 max-w-4xl pt-4">
          <CareerTimeline timeline={profile.career_timeline} />
          <EntityGrids 
            education={profile.education}
            philanthropy={profile.philanthropy}
            affiliations={profile.affiliations}
          />
        </div>

        <div className="pt-8">
          <SourcesPanel sources={profile.sources_master_list} />
        </div>
        
      </main>

      {/* Disclaimer Footer */}
      <footer className="bg-[#0a2540] text-slate-300 py-8 mt-12 border-t border-[#0a2540]">
        <div className="max-w-[1200px] mx-auto px-6 text-center">
          <p className="text-sm opacity-80 max-w-3xl mx-auto leading-relaxed">
            <strong className="text-white">AI-Assisted Research:</strong> This profile was generated by AI agents querying public data sources. 
            While credibility tiers and confidence flags are applied, you must verify all claims independently 
            before use in compliance, legal, or investment decisions.
          </p>
        </div>
      </footer>
    </div>
  )
}
