import * as React from "react"
import { DiligenceProfile } from "@/types/profile"
import { ProfileHeader } from "./ProfileHeader"
import { NetWorthCard } from "./NetWorthCard"
import { CareerTimeline } from "./CareerTimeline"
import { EntityGrids } from "./EntityGrids"
import { ConcernsPanel } from "./ConcernsPanel"
import { SourcesPanel } from "./SourcesPanel"
import { ShieldCheck } from "lucide-react"
import Link from "next/link"

export function ProfileDashboard({ profile }: { profile: DiligenceProfile }) {
  return (
    <div className="min-h-screen bg-background">
      {/* Top Navbar */}
      <header className="bg-white border-b border-gray-200 sticky top-0 z-10">
        <div className="max-w-7xl mx-auto px-4 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2 hover:opacity-80 transition-opacity">
            <div className="bg-primary p-1.5 rounded-md">
              <ShieldCheck className="h-5 w-5 text-white" />
            </div>
            <span className="font-bold text-primary text-lg tracking-tight">Diligencify</span>
          </Link>
          <div className="text-sm font-medium text-muted bg-gray-100 px-3 py-1 rounded-full">
            Profile Report
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-7xl mx-auto px-4 py-8 space-y-8">
        
        <ConcernsPanel concerns={profile.concerns} />

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          <div className="lg:col-span-2 space-y-8">
            <ProfileHeader profile={profile} />
            <CareerTimeline timeline={profile.career_timeline} />
            <EntityGrids 
              education={profile.education}
              philanthropy={profile.philanthropy}
              affiliations={profile.affiliations}
            />
          </div>
          <div className="space-y-8">
            <NetWorthCard netWorth={profile.net_worth} />
            {/* Aditional sidebar items could go here */}
          </div>
        </div>

        <SourcesPanel sources={profile.sources_master_list} />
        
      </main>

      {/* Disclaimer Footer */}
      <footer className="bg-primary text-primary-50 py-6 mt-12 border-t border-primary-800">
        <div className="max-w-7xl mx-auto px-4 text-center">
          <p className="text-sm opacity-80 max-w-2xl mx-auto">
            <strong>AI-Assisted Research:</strong> This profile was generated by AI agents querying public data sources. 
            While credibility tiers and confidence flags are applied, you must verify all claims independently 
            before use in compliance, legal, or investment decisions.
          </p>
        </div>
      </footer>
    </div>
  )
}
